[package]
name = "asysounds_core"
version = "0.1.2"
edition = "2024"

[dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_Media_Audio", "Win32_System_Com", "Win32_UI_Shell_PropertiesSystem", "Win32_Devices_FunctionDiscovery", "Win32_System_Threading"] }
cpal = "0.18.2"
ringbuf = "0.5.2"
nnnoiseless = { version = "0.5.2", default-features = false }
